version: "10.3"
services:
  mysql:
    image: mariadb
    container_name: workout
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: workout
      MYSQL_DATABASE: 'workout'
      MYSQL_USER: 'workout'
      MYSQL_PASSWORD: 'workout'
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: workout_phpmyadmin1
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"