# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

inhibit_all_warnings!

target 'QuickTrain-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-MVVM
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Reusable'
  pod 'RxNuke'
  pod 'RxOptional'
  pod 'Defaults'
  pod 'SnapKit'
  pod 'Hero'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftDate'
  pod 'NVActivityIndicatorView', '~> 4.8.0'
  pod 'NotificationBannerSwift'
  pod 'PopupDialog'
  pod 'SwiftLint'
  pod 'CleanroomLogger'
  pod 'Wormholy'
  pod 'SwiftGen'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'Kingfisher', '~> 5.15'
  pod 'youtube-ios-player-helper'
  pod 'SwiftGen'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'GrowingTextView', '0.7.2'
  pod "RxRealm"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['CleanroomLogger'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
